docker-compose-yaml: docker-compose.yml

cronjobs:
  - name: drush cron
    schedule: "*/15 * * * *"
    command: drush cron
    service: cli

environments:
  master:
    routes:
      - varnish:
        - "accn.wiche.edu":
           tls-acme: 'true'
           insecure: Redirect
        - "adultcollegecompletion.org":
           tls-acme: 'true'
           insecure: Redirect        
